#pds_blog_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: pdsBlogBundle:Default:index }

pds_blog_homepage:
    pattern: /
    defaults: { _controller: pdsBlogBundle:Blog:index }
    
pds_blog_article:
    path: /article/{id}
    defaults: { _controller: pdsBlogBundle:Article:article }
    
pds_blog_comment_add:
    path: /comment/add
    defaults: { _controller: pdsBlogBundle:Comment:add }