parameters:
#    pds_blog.example.class: pds\BlogBundle\Example

services:
#    pds_blog.example:
#        class: %pds_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]